name: Build CeGCC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y \
            git build-essential bison flex m4 \
            libgmp-dev libmpc-dev libmpfr-dev texinfo \
            coreutils findutils sed grep unzip zip

      - name: Clone cegcc-build & wincepython3
        run: |
          git clone --recursive --depth 1 https://github.com/MaxKellermann/cegcc-build.git
          git clone https://github.com/brain-hackers/cpython-wince.git

      - name: Create install and build directories
        run: |
          mkdir -p /tmp/cegcc-output
          mkdir -p $HOME/cegcc-install

      - name: Build CeGCC
        run: |
          cd /tmp/cegcc-output
          $GITHUB_WORKSPACE/cegcc-build/build.sh -j$(nproc) --prefix=$HOME/cegcc-install

      - name: Build PythonCE and pack
        env:
          PATH: $HOME/cpython-wince/bin:$PATH
        run: |
          cd $GITHUB_WORKSPACE/cpython-wince
          chmod +x ce_build.sh ce_pack.sh ce_clean.sh || true
          ./ce_build.sh
          ./ce_pack.sh
          zip -r wince_build.zip build/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wince_build
          path: ${{ github.workspace }}/cpython-wince/wince_build.zip
